"""Public protocols and version for Repo Agent."""

from pathlib import Path
from typing import Any, Protocol

__version__ = "0.1.0"
package_dir = Path(__file__).resolve().parent


class Model(Protocol):
    def query(self, messages: list[dict]) -> dict: ...
    def format_message(self, content: str, actions: list[dict] | None = None) -> dict: ...
    def format_observation_messages(self, message: dict, outputs: list[Any], template_vars: dict | None = None) -> list[dict]: ...
    def get_template_vars(self, **kwargs) -> dict: ...
    def serialize(self) -> dict: ...


class Environment(Protocol):
    def execute(self, action: dict | str) -> Any: ...
    def find_files(self, filename: str) -> list[str]: ...
    def serialize(self) -> dict: ...
    def get_template_vars(self, **kwargs) -> dict: ...


class Agent(Protocol):
    def run(self, task: str, **kwargs) -> Any: ...
    def resume(self, task: str, trajectory: dict) -> Any: ...
    def serialize(self) -> dict: ...
    def save(self, path: Path) -> None: ...


from .result import AgentResult, AgentStatus

__all__ = ["Agent", "AgentResult", "AgentStatus", "Environment", "Model", "__version__", "package_dir"]
